# Project: examples
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Sqlist_9.o Sqlist_10.o
LINKOBJ  = Sqlist_9.o Sqlist_10.o
LIBS     = -L"D:/DEV/Dev-Cpp/MinGW64/lib" -L"D:/DEV/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/DEV/Dev-Cpp/MinGW64/include" -I"D:/DEV/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DEV/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/DEV/Dev-Cpp/MinGW64/include" -I"D:/DEV/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DEV/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/DEV/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = examples.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Sqlist_9.o: Sqlist_9.cpp
	$(CPP) -c Sqlist_9.cpp -o Sqlist_9.o $(CXXFLAGS)

Sqlist_10.o: Sqlist_10.cpp
	$(CPP) -c Sqlist_10.cpp -o Sqlist_10.o $(CXXFLAGS)
